camel:
  service:
    lra:
      enabled: true
      coordinator-url: http://localhost:8080
      local-participant-url: http://localhost:8082 #важно определить root context, иначе при callback будет 404

